name: Test

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.2.1
      with:
        prefix-key: ""
        shared-key: ${{ hashFiles('Cargo.lock') }}
        key: ""
    - name: Build
      run: cargo build --workspace
    - name: Run tests
      run: cargo test --workspace
#      run: RUST_BACKTRACE=1 cargo test --workspace -- --nocapture --test-threads=1
